In [1]:
from google.cloud import bigquery
import pandas as pd
import os
import sys

caminho_absoluto = os.path.abspath(os.curdir)
sys.path.insert(0, caminho_absoluto)
print(f"Caminho absoluto adicionado ao sys.path: {sys.path}")
#from database.repositories import EstacoesRepository

Caminho absoluto adicionado ao sys.path: ['c:\\Users\\RafaelLuizGonçalvesS\\Desktop\\PesquisaDadosGNSS\\EstudoGNSS', 'c:\\Users\\RafaelLuizGonçalvesS\\AppData\\Local\\Programs\\Python\\Python312\\python312.zip', 'c:\\Users\\RafaelLuizGonçalvesS\\AppData\\Local\\Programs\\Python\\Python312\\DLLs', 'c:\\Users\\RafaelLuizGonçalvesS\\AppData\\Local\\Programs\\Python\\Python312\\Lib', 'c:\\Users\\RafaelLuizGonçalvesS\\AppData\\Local\\Programs\\Python\\Python312', '', 'C:\\Users\\RafaelLuizGonçalvesS\\AppData\\Roaming\\Python\\Python312\\site-packages', 'c:\\Users\\RafaelLuizGonçalvesS\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages']

In [2]:
chave = r"C:\Users\RafaelLuizGonçalvesS\Downloads\pure-lodge-464519-d5-abf8344703b5.json"


client = bigquery.Client.from_service_account_json(chave)

query = """
    SELECT 
        id_municipio,
        id_estacao,
        estacao,
        data_fundacao,
        latitude,
        longitude,
        altitude 
    FROM `basedosdados.br_inmet_bdmep.estacao` 
"""

resultado = client.query(query)

# Dica: usar o .to_dataframe() é muito mais rápido e organizado para ver os dados
df = resultado.to_dataframe()
df.head()

c:\Users\RafaelLuizGonçalvesS\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,id_municipio,id_estacao,estacao,data_fundacao,latitude,longitude,altitude
0,5300108,A001,Brasilia,2000-05-07,-15.789444,-47.925833,1160.96
1,5300108,A042,Brazlandia,2017-07-19,-15.599722,-48.131111,1143.00
2,5300108,A045,Aguas Emendadas,2008-10-03,-15.596491,-47.625801,1030.36
3,5300108,A046,Gama (Ponte Alta),2014-10-01,-15.935278,-48.137500,990.00
4,5300108,A047,Paranoa (Coopa-Df),2017-02-07,-16.012222,-47.557417,1043.00

In [ ]:
chave = r"C:\Users\RafaelLuizGonçalvesS\Downloads\pure-lodge-464519-d5-abf8344703b5.json"


client = bigquery.Client.from_service_account_json(chave)

query = """
    SELECT 
        *
    FROM `basedosdados.br_inmet_bdmep.microdados`
    WHERE id_estacao = 'F501'
"""

resultado = client.query(query)

# Dica: usar o .to_dataframe() é muito mais rápido e organizado para ver os dados
df_coleta = resultado.to_dataframe()

c:\Users\RafaelLuizGonçalvesS\AppData\Local\Programs\Python\Python312\Lib\site-packages\google\cloud\bigquery\table.py:1994: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,ano,mes,data,hora,id_estacao,precipitacao_total,pressao_atm_hora,pressao_atm_max,pressao_atm_min,radiacao_global,...,temperatura_max,temperatura_min,temperatura_orvalho_max,temperatura_orvalho_min,umidade_rel_max,umidade_rel_min,umidade_rel_hora,vento_direcao,vento_rajada_max,vento_velocidade
0,2015,1,2015-01-05,02:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,6,2015-06-16,13:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,7,2015-07-15,02:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,12,2015-12-29,09:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,12,2015-12-29,08:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df_coleta.head(10)

,ano,mes,data,hora,id_estacao,precipitacao_total,pressao_atm_hora,pressao_atm_max,pressao_atm_min,radiacao_global,...,temperatura_max,temperatura_min,temperatura_orvalho_max,temperatura_orvalho_min,umidade_rel_max,umidade_rel_min,umidade_rel_hora,vento_direcao,vento_rajada_max,vento_velocidade
0,2015,1,2015-01-05,02:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2015,6,2015-06-16,13:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2015,7,2015-07-15,02:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2015,12,2015-12-29,09:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2015,12,2015-12-29,08:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2015,12,2015-12-29,07:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2015,12,2015-12-29,06:00:00,F501,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2015,9,2015-09-19,16:00:00,F501,0.0,883.7,884.6,883.7,3621.7,...,32.0,29.8,5.2,-5.3,20.0,NaN,11.0,90.0,10.1,6.2
8,2015,9,2015-09-19,17:00:00,F501,0.0,883.0,883.7,883.0,3299.0,...,32.2,31.0,-0.5,-4.2,13.0,10.0,13.0,118.0,10.1,4.2
9,2015,10,2015-10-15,17:00:00,F501,0.0,882.1,882.7,882.1,3396.3,...,33.7,31.1,3.8,-0.4,17.0,12.0,13.0,35.0,7.5,2.8

In [17]:
df_coleta.to_csv('dados_coleta_BH.csv', index=False)

In [3]:
df.to_csv('estacoes.csv', index=False)

In [9]:
df.query('estacao == "Monte Carmelo"')

Empty DataFrame
Columns: [id_municipio, id_estacao, estacao, data_fundacao, latitude, longitude, altitude]
Index: []

In [15]:
for index, row in df.iterrows():
    if "Belo" in row["estacao"]:
        print(row["estacao"])
        print(row["id_estacao"])

Belo Horizonte - Cercadinho
F501